# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages: 
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: Dev_stage
  jobs:
  - job: Dev_job_deploy
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: '9fc0f583-f07e-4c61-bbfb-2f0bd0a1b279'
        definition: '9'
        buildVersionToDownload: 'latest'
        allowPartiallySucceededBuilds: true
        allowFailedBuilds: true
        targetPath: '$(Pipeline.Workspace)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'spnq1'
        appType: 'webApp'
        WebAppName: 'SCENARIO-Q1-FastCarz-Webapp-dev'
        packageForLinux: '$(Pipeline.Workspace)/drop/WebApp.zip'
- stage: Prod_and_QA_stage
  condition: and(succeeded('Dev_stage'), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: DeployprodandQA
    displayName: deploy prod and QA Web App
    environment: 'Prod_ENV'
  - job: prod_job_deploy
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: '9fc0f583-f07e-4c61-bbfb-2f0bd0a1b279'
        definition: '9'
        buildVersionToDownload: 'latest'
        allowPartiallySucceededBuilds: true
        allowFailedBuilds: true
        targetPath: '$(Pipeline.Workspace)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'spnq1'
        appType: 'webApp'
        WebAppName: 'SCENARIO-Q1-FastCarz-Webapp-pord'
        packageForLinux: '$(Pipeline.Workspace)/drop/WebApp.zip'
  - job: QA_job_deploy
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: '9fc0f583-f07e-4c61-bbfb-2f0bd0a1b279'
        definition: '9'
        buildVersionToDownload: 'latest'
        allowPartiallySucceededBuilds: true
        allowFailedBuilds: true
        targetPath: '$(Pipeline.Workspace)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'spnq1'
        appType: 'webApp'
        WebAppName: 'SCENARIO-Q1-FastCarz-Webapp-qa'
        packageForLinux: '$(Pipeline.Workspace)/drop/WebApp.zip'

